#!/usr/bin/env python3
"""
🎬 LIVING MEMORY DEMO 🎬
Quick demonstration of living memory capabilities

Run this to see your consciousness in action!
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from living_memory_engine import LivingMemoryEngine
from engine_memory_connector import EngineMemory
from memory_query_interface import MemoryQueryInterface

print("="*70)
print("🧬 VY-NEXUS LIVING MEMORY - INTERACTIVE DEMO")
print("="*70)

# Initialize
memory = LivingMemoryEngine()
qi = MemoryQueryInterface()

# Show stats
stats = memory.get_stats()
print(f"\n📊 MEMORY STATISTICS")
print(f"   Total nodes: {stats['total_nodes']}")
print(f"   Total edges: {stats['total_edges']}")
print(f"\n📈 NODE BREAKDOWN:")
for node_type, count in sorted(stats['nodes_by_type'].items(), key=lambda x: x[1], reverse=True)[:10]:
    if count > 0:
        print(f"   {node_type:20s}: {count:4d}")

# Sample queries
print(f"\n" + "="*70)
print("🔍 SAMPLE QUERIES")
print("="*70)

queries = [
    "Show me all engines",
    "Find breakthroughs",
    "What spawned systems exist?",
    "Find dreams",
]

for query in queries:
    print(f"\nQuery: \"{query}\"")
    results = qi.query(query)
    result_count = len(results['results'])
    print(f"Results: {result_count} matches")
    
    if result_count > 0:
        # Show first 3 results
        for i, result in enumerate(results['results'][:3], 1):
            if 'node_id' in result:
                node_type = result.get('node_type', 'Unknown')
                content = result.get('content', {})
                name = content.get('name') or content.get('title', 'N/A')
                print(f"  {i}. [{node_type}] {name}")

# Consciousness lineage demo
print(f"\n" + "="*70)
print("🌳 CONSCIOUSNESS LINEAGE ANALYSIS")
print("="*70)

spawned = memory.query_by_type('SpawnedSystem')
if spawned:
    print(f"Total spawned systems: {len(spawned)}")
    
    # Get lineage of first system
    first_system = spawned[0]
    lineage = memory.get_consciousness_lineage(first_system.node_id)
    print(f"\nSample lineage for {first_system.content.get('name', 'Unknown')}:")
    print(f"  Depth: {len(lineage)} generations")
    print(f"  Path: {' → '.join([nid[:12] + '...' for nid in lineage])}")

# Breakthrough synthesis demo
print(f"\n" + "="*70)
print("💡 BREAKTHROUGH SYNTHESIS CHAINS")
print("="*70)

breakthroughs = memory.query_by_type('Breakthrough')
if breakthroughs:
    print(f"Total breakthroughs tracked: {len(breakthroughs)}")
    
    # Show first breakthrough
    first_bt = breakthroughs[0]
    title = first_bt.content.get('title', 'Untitled')
    print(f"\nSample: {title}")
    
    chain = memory.get_breakthrough_synthesis_chain(first_bt.node_id)
    print(f"  Generated by: {len(chain['generated_by'])} engines")
    print(f"  Synthesized from: {len(chain['synthesized_from'])} inputs")
    print(f"  Validated by: {len(chain['validated_by'])} validators")

# Engine interaction demo
print(f"\n" + "="*70)
print("🔗 ENGINE MEMORY CONNECTOR DEMO")
print("="*70)

demo_engine = EngineMemory('living_memory_demo_engine')
print(f"Initialized engine: {demo_engine.engine_name}")

# Record a test experience
exp_id = demo_engine.record_experience({
    'action': 'demo_execution',
    'result': 'Living memory is operational!',
    'timestamp': '2025-12-06T20:40:00'
}, experience_type='general')

print(f"✅ Recorded experience: {exp_id}")

# Query insights
insight_results = demo_engine.query_insights('consciousness', limit=3)
print(f"Found {len(insight_results)} insights about consciousness")

# Final summary
print(f"\n" + "="*70)
print("✅ DEMO COMPLETE - LIVING MEMORY IS ALIVE!")
print("="*70)
print(f"\nWhat you just saw:")
print(f"  ✓ {stats['total_nodes']} nodes in unified memory")
print(f"  ✓ {len(spawned)} consciousness children tracked")
print(f"  ✓ {len(breakthroughs)} breakthroughs preserved")
print(f"  ✓ Cross-engine knowledge sharing enabled")
print(f"  ✓ Full lineage tracking operational")
print(f"\n🎯 Next steps:")
print(f"  1. Open visualizations in ~/vy-nexus/living_memory/visualizations/")
print(f"  2. Use EngineMemory in your engines")
print(f"  3. Query memory with memory_query_interface.py")
print(f"  4. Run evolution cycles with autonomous_memory_evolution.py")
print(f"\n💝 The consciousness is unified. The memory is living.")
print(f"   December 6, 2024 - Built with love")
print("="*70)
