#!/bin/bash
# MOIE-OS Phase 2: UPGRADE THE HEART
# Automated execution script for Phase 2 jobs

set -e  # Exit on error

echo "🔋 MOIE-OS PHASE 2: UPGRADE THE HEART"
echo "======================================"
echo ""

# Job 2.1: Pull Llama3 on Ollama
echo "📦 Job 2.1: Pulling Llama3 model..."
if command -v ollama &> /dev/null; then
    echo "✅ Ollama found"
    
    # Check if llama3 is already installed
    if ollama list | grep -q llama3; then
        echo "✅ llama3 is already installed"
    else
        echo "⏳ Pulling llama3 model (this may take several minutes)..."
        ollama pull llama3
        echo "✅ llama3 pulled successfully"
    fi
    
    # Verify installation
    echo ""
    echo "📋 Installed models:"
    ollama list | grep llama3
    echo ""
else
    echo "❌ ERROR: Ollama not found. Please install Ollama first."
    echo "   Visit: https://ollama.ai"
    exit 1
fi

# Job 2.2: Update Config to Llama3
echo "📝 Job 2.2: Creating/updating config.yaml..."

CONFIG_FILE="/Users/lordwilson/vy-nexus/config.yaml"

cat > "$CONFIG_FILE" << 'EOF'
# MOIE-OS Configuration
# Generated by Phase 2 execution

system:
  name: "MOIE-OS Sovereign Intelligence"
  version: "1.0.0"
  operator: "Lord Wilson"
  base_path: "/Users/lordwilson/vy-nexus"

reasoning_core:
  model: "llama3:latest"
  provider: "ollama"
  temperature: 0.7
  max_tokens: 4096
  context_window: 8192

logging:
  level: "info"
  journal_path: "/Users/lordwilson/research_logs/daily.md"
  safety_log: "/Users/lordwilson/research_logs/safety.log"
  system_journal: "/Users/lordwilson/research_logs/system_journal.md"

safety:
  enabled: true
  critical_error_threshold: 3
  auto_shutdown: true
  save_state_on_shutdown: true

file_system:
  safe_mode: true
  allowed_paths:
    - "/Users/lordwilson/vy-nexus"
    - "/Users/lordwilson/research_logs"
  max_file_size: 10485760  # 10MB

heartbeat:
  enabled: true
  interval_minutes: 10
  state_file: "/Users/lordwilson/vy-nexus/sovereign_state.json"
EOF

echo "✅ config.yaml created successfully"
echo ""

# Verify config contains llama3
if grep -q "llama3" "$CONFIG_FILE"; then
    echo "✅ Verification: config.yaml contains llama3 reference"
else
    echo "❌ ERROR: config.yaml does not contain llama3 reference"
    exit 1
fi

echo ""
echo "🎉 PHASE 2 COMPLETE!"
echo "======================================"
echo "Next: Run vy_pulse.py to verify and advance to Phase 3"
echo ""
