/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'RecursivePlanner': EventHandler<never, { topic: 'agent.plan'; data: never } | { topic: 'agent.complete'; data: never } | { topic: 'agent.research'; data: never } | { topic: 'engineer.build'; data: never }>
    'OmniKernel': EventHandler<never, { topic: 'agent.log'; data: never }>
    'NanoObserver': EventHandler<never, { topic: 'agent.log'; data: never }>
    'NanoMutator': EventHandler<never, { topic: 'agent.log'; data: never } | { topic: 'fs.mutation.success'; data: never } | { topic: 'fs.mutation.error'; data: never }>
    'NanoEdit': EventHandler<never, { topic: 'code.modified'; data: never } | { topic: 'code.failure'; data: never }>
    'EpistemicResearcher': EventHandler<never, { topic: 'research.result'; data: never }>
    'DevLogger': EventHandler<never, never>
    'AutonomousEngineer': EventHandler<never, { topic: 'agent.log'; data: never } | { topic: 'engineer.success'; data: never } | { topic: 'engineer.failure'; data: never }>
  }
    
}