// Core type definitions for Motia DSIE Spine

/**
 * Individual step in a Motia execution plan
 */
export interface MotiaStep {
  id: string;
  description: string;
  tool: 'edit_file' | 'run_command' | 'call_api' | 'analyze' | 'git_operation' | 'filesystem_read' | 'filesystem_write';
  params: Record<string, any>;
  dependencies?: string[]; // IDs of steps this depends on
  optional?: boolean; // Can this step be skipped if it fails?
}

/**
 * Complete execution plan generated by the planner
 */
export interface MotiaPlan {
  goal: string;
  steps: MotiaStep[];
  metadata?: {
    plannerVersion: string;
    timestamp: string;
    estimatedDuration?: number;
    complexity?: 'low' | 'medium' | 'high';
  };
}

/**
 * Result of executing a single step
 */
export interface StepResult {
  stepId: string;
  success: boolean;
  output?: any;
  error?: string;
  duration: number;
  timestamp: string;
}

/**
 * Complete execution result
 */
export interface ExecutionResult {
  planId: string;
  success: boolean;
  stepResults: StepResult[];
  totalDuration: number;
  completedSteps: number;
  failedSteps: number;
  skippedSteps: number;
}

/**
 * Repository context for planning
 */
export interface RepoContext {
  rootPath: string;
  files: string[];
  gitStatus?: {
    branch: string;
    hasChanges: boolean;
    remoteUrl?: string;
  };
  packageInfo?: {
    name: string;
    version: string;
    dependencies: Record<string, string>;
  };
  structure?: {
    directories: string[];
    mainFiles: string[];
  };
}

/**
 * Planning request input
 */
export interface PlanningRequest {
  goal: string;
  context: RepoContext;
  constraints?: {
    maxSteps?: number;
    timeLimit?: number;
    safeMode?: boolean;
  };
}