import type { StepConfig, StepHandler } from 'motia';

export const config: StepConfig = {
  name: 'RecursivePlanner',
  type: 'event',
  subscribes: ['agent.plan', 'research.result'],
  emits: ['agent.plan', 'agent.complete', 'agent.research', 'engineer.build'],
};

type PlanEvent = {
  goal: string;
  depth?: number;
  history?: string[];
};

export const handler: StepHandler = async (event, ctx) => {
  const { emit, logger } = ctx;

  // Branch 1: research results coming back
  if (event.topic === 'research.result') {
    const { findings, originalQuery } = event.data as {
      findings: string;
      originalQuery: string;
    };

    logger.info(`🧠 Planner: integrating research for "${originalQuery}"`);
    await emit({
      topic: 'agent.plan',
      data: {
        goal: `Synthesize findings for: ${originalQuery}`,
        depth: 0,
        history: [`Research Found: ${findings}`],
      },
    });
    return { status: 'knowledge_integrated' };
  }

  // Branch 2: normal planning
  const { goal, depth = 0, history = [] } = event.data as PlanEvent;

  if (depth > 10) {
    logger.warn(`🧠 Planner: max depth reached for "${goal}"`);
    return { status: 'terminated' };
  }

  // Heuristic: any "Research/Find/Check" goal → EpistemicResearcher
  if (/(Research|Find|Check)/i.test(goal)) {
    logger.info(`🕵️‍♀️ Planner → EpistemicResearcher: ${goal}`);
    await emit({
      topic: 'agent.research',
      data: {
        query: goal,
        contextId: 'root',
      },
    });
    return { status: 'delegated_to_researcher' };
  }

  // Heuristic: simple "Write" goal → AutonomousEngineer in sandbox
  if (/^Write\s+/i.test(goal)) {
    logger.info(`👷 Planner → AutonomousEngineer (sandbox): ${goal}`);
    const parts = goal.split(/\s+/);
    const maybePath = parts[parts.length - 1] || 'scratch/auto-generated.ts';
    const safePath = maybePath.startsWith('scratch/')
      ? maybePath
      : `scratch/${maybePath.replace(/^\.?\/*/, '')}`;

    await emit({
      topic: 'engineer.build',
      data: {
        filePath: safePath,
        code: `// Auto-generated by RecursivePlanner\nconsole.log("Hello from ${safePath}");\n`,
        testCommand: `node ${safePath}`,
        attempt: 1,
      },
    });

    return { status: 'delegated_to_engineer', target: safePath };
  }

  // Otherwise: just complete the goal
  logger.info(`✅ Planner: completing goal "${goal}"`);
  await emit({
    topic: 'agent.complete',
    data: { goal, result: 'Executed', history },
  });

  return { status: 'completed' };
};