#!/bin/bash
# Build Verification Script
# Generated by BACKGROUND VY at 2025-12-17 08:00 PST

cd "$(dirname "$0")"

echo "================================================================================"
echo "CARGO BUILD --WORKSPACE"
echo "================================================================================"
echo ""

cargo build --workspace 2>&1
BUILD_EXIT=$?

echo ""
echo "Build exit code: $BUILD_EXIT"
echo ""

if [ $BUILD_EXIT -eq 0 ]; then
    echo "================================================================================"
    echo "CARGO TEST --WORKSPACE"
    echo "================================================================================"
    echo ""
    
    cargo test --workspace 2>&1
    TEST_EXIT=$?
    
    echo ""
    echo "Test exit code: $TEST_EXIT"
    echo ""
    
    if [ $TEST_EXIT -eq 0 ]; then
        echo "✓ ALL TESTS PASSED"
        exit 0
    else
        echo "✗ TESTS FAILED"
        exit $TEST_EXIT
    fi
else
    echo "✗ BUILD FAILED - Skipping tests"
    exit $BUILD_EXIT
fi
