#!/usr/bin/env python3
"""
nano_draft.py - Create improvement drafts from nano snippets
"""

import json
import os
import uuid
from datetime import datetime
from pathlib import Path

def load_index():
    """Load and parse index.jsonl"""
    nano_memory = Path.home() / 'nano_memory'
    index_file = nano_memory / 'index.jsonl'
    
    if not index_file.exists():
        print(f"[!] No index.jsonl found at {index_file}")
        return []
    
    entries = []
    with open(index_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"[!] Error parsing line: {line} - {e}")
    
    return entries

def load_nano_file(nano_file_path):
    """Load content from a .nano file"""
    try:
        with open(nano_file_path, 'r') as f:
            content = f.read()
            # Handle both JSON and plain text formats
            if content.strip().startswith('{'):
                return json.loads(content)
            else:
                # Parse plain text format
                lines = content.strip().split('\n')
                data = {}
                snippet_lines = []
                in_snippet = False
                
                for line in lines:
                    if line.startswith('# '):
                        key, value = line[2:].split(': ', 1)
                        data[key] = value
                    elif line.startswith('def ') or in_snippet:
                        in_snippet = True
                        snippet_lines.append(line)
                
                data['snippet'] = '\n'.join(snippet_lines)
                return data
    except Exception as e:
        print(f"[!] Error loading {nano_file_path}: {e}")
        return None

def create_draft(source_entry, source_data):
    """Create an improvement draft"""
    nano_memory = Path.home() / 'nano_memory'
    
    # Generate new UUID for draft
    draft_id = str(uuid.uuid4()).replace('-', '')[:8]
    timestamp = datetime.now().strftime('%Y-%m-%dT%H-%M-%S')
    draft_filename = f"{timestamp}_draft_{draft_id}.nano"
    draft_path = nano_memory / draft_filename
    
    # Create draft content
    draft_data = {
        "type": "improvement_draft",
        "source_chunk_id": source_entry.get('chunk_id', source_entry.get('hash', 'unknown')),
        "source_nano_file": source_entry['nano_file'],
        "source_path": source_data.get('source_path', source_entry.get('source_path', 'unknown')),
        "function": source_data.get('function', source_entry.get('function', 'unknown')),
        "original_snippet": source_data.get('snippet', 'def add(a, b): ...'),
        "proposed_change": "DRAFT: Proposed improvement generated by NanoApex. This is a placeholder for the actual AI-generated improvement.",
        "status": "DRAFT",
        "created_at": timestamp
    }
    
    # Write draft file
    with open(draft_path, 'w') as f:
        json.dump(draft_data, f, indent=2)
    
    # Update index.jsonl
    index_file = nano_memory / 'index.jsonl'
    index_entry = {
        "kind": "draft",
        "chunk_id": draft_id,
        "nano_file": draft_filename,
        "source_chunk_id": source_entry.get('chunk_id', source_entry.get('hash', 'unknown')),
        "source_path": source_data.get('source_path', source_entry.get('source_path', 'unknown')),
        "function": source_data.get('function', source_entry.get('function', 'unknown')),
        "status": "DRAFT",
        "created_at": timestamp
    }
    
    with open(index_file, 'a') as f:
        f.write(json.dumps(index_entry) + '\n')
    
    return draft_path, draft_filename

def main():
    print("=== Nano Draft Generator ===")
    
    # Load index
    entries = load_index()
    if not entries:
        print("[!] No entries found in index.jsonl")
        return
    
    # Filter for snippet entries
    snippet_entries = [e for e in entries if e.get('kind') == 'snippet']
    
    if not snippet_entries:
        print("[!] No snippet entries found in index.jsonl")
        return
    
    # Display available snippets
    print("\nAvailable snippets:")
    for i, entry in enumerate(snippet_entries):
        function = entry.get('function', 'unknown')
        source_path = entry.get('source_path', 'unknown')
        nano_file = entry.get('nano_file', 'unknown')
        print(f"[{i}] {function} from {source_path} ({nano_file})")
    
    # Get user selection
    try:
        selection = input("\nSelect index to draft for: ").strip()
        index = int(selection)
        
        if index < 0 or index >= len(snippet_entries):
            print("[!] Invalid selection")
            return
        
        selected_entry = snippet_entries[index]
        
    except (ValueError, KeyboardInterrupt):
        print("\n[!] Invalid input or cancelled")
        return
    
    # Load the nano file content
    nano_memory = Path.home() / 'nano_memory'
    nano_file_path = nano_memory / selected_entry['nano_file']
    
    if not nano_file_path.exists():
        print(f"[!] Nano file not found: {nano_file_path}")
        return
    
    source_data = load_nano_file(nano_file_path)
    if not source_data:
        print(f"[!] Could not load nano file: {nano_file_path}")
        return
    
    # Create draft
    try:
        draft_path, draft_filename = create_draft(selected_entry, source_data)
        print(f"\n[✓] Draft created: {draft_path}")
        print(f"[+] Indexed draft in index.jsonl as kind='draft'.")
        
    except Exception as e:
        print(f"[!] Error creating draft: {e}")

if __name__ == '__main__':
    main()