/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StatusAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'SparkEntrypoint': EventHandler<never, { topic: 'agent.plan'; data: never }>
    'SafetyHandler': EventHandler<never, never>
    'RecursivePlanner': EventHandler<never, { topic: 'agent.plan'; data: never } | { topic: 'agent.complete'; data: never } | { topic: 'agent.research'; data: never }>
    'PhysicalHand': EventHandler<never, never>
    'OmniKernel': EventHandler<never, { topic: 'agent.plan'; data: never } | { topic: 'agent.execute'; data: never } | { topic: 'system.prune'; data: never } | { topic: 'kernel.panic'; data: never }>
    'NanoEdit': EventHandler<never, { topic: 'code.modified'; data: never }>
    'MainExecutor': EventHandler<never, { topic: 'agent.complete'; data: never } | { topic: 'physical.action'; data: never } | { topic: 'code.modify'; data: never }>
    'LoveGateway': EventHandler<never, { topic: 'agent.validated'; data: never } | { topic: 'agent.rejected'; data: never }>
    'HealthAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GenesisKernel': EventHandler<never, { topic: 'agent.plan'; data: never } | { topic: 'agent.execute'; data: never } | { topic: 'system.prune'; data: never } | { topic: 'kernel.panic'; data: never }>
    'EpistemicResearcher': EventHandler<never, { topic: 'research.result'; data: never }>
    'EngageAPI': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'user.input'; data: never }>
    'CompletionHandler': EventHandler<never, never>
    'CodeHealthcheck': EventHandler<never, never>
    'AutoSpark': EventHandler<never, { topic: 'user.input'; data: never }>
  }
    
}